from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

from req2code.config import AgentConfig
from req2code.models import TaskType, WorkItem
from req2code.repository import RepositoryError, RepositorySpec
from req2code.run_state import RunStatus
from req2code.workflow import WorkflowService

from test_repository import create_remote, git


MEMORY = """## OVERVIEW
Demo service.
## ARCHITECTURE
Single module.
## MODULES
implemented.txt is generated by the task.
## DEVELOPMENT
Keep changes focused.
## TESTING
Run the configured tests.
## RISKS
Do not commit from the agent.
"""


class FakeRunner:
    session_id = "fake-session"

    def set_project_context(self, context):
        self.project_context = context

    def understand_project(self, work_item, target_dir, **kwargs):
        return MEMORY

    def candidate_project_memory(self, work_item, target_dir, existing_memory, changed_files, diff, test_details):
        return MEMORY.replace("Demo service.", "Demo service with approved implementation.")
    def analyze(self, work_item, target_dir):
        return "[Analyze OK]\nImplement one focused file and test it."

    def develop(self, work_item, target_dir, analysis=""):
        Path(target_dir, "implemented.txt").write_text("done\n", encoding="utf-8")
        return "[Develop OK]\nCreated implemented.txt"

    def fix(self, work_item, target_dir, test_details):
        return "[Fix OK]"

    def review(self, work_item, target_dir, diff):
        return "PASS"


class CommittingRunner(FakeRunner):
    def develop(self, work_item, target_dir, analysis=""):
        target = Path(target_dir)
        (target / "agent-commit.txt").write_text("committed by agent\n", encoding="utf-8")
        subprocess.run(["git", "add", "agent-commit.txt"], cwd=target, check=True)
        subprocess.run(
            ["git", "-c", "user.name=Agent", "-c", "user.email=agent@example.com", "commit", "-m", "agent commit"],
            cwd=target,
            check=True,
            capture_output=True,
        )
        return "[Develop OK]"


def test_workflow_waits_for_approval_before_commit_and_push(tmp_path, monkeypatch):
    remote = create_remote(tmp_path)
    cfg = AgentConfig()
    cfg.system.state_dir = str(tmp_path / "state")
    cfg.engines.codex.command = f'"{sys.executable}"'
    cfg.review.approvals_file = str(tmp_path / "approvals.yaml")
    cfg.message.webhook = ""
    cfg.testing.unit_command = 'python -c "print(1)"'
    cfg.testing.script_command = ""
    cfg.testing.coverage_command = 'python -c "print(\'TOTAL 1 0 100%\')"'
    cfg.testing.min_coverage = 80

    service = WorkflowService(cfg)
    monkeypatch.setattr(service, "_runner", lambda engine=None: (FakeRunner(), "codex"))
    item = WorkItem(id="TAPD-1", title="Feature", description="Implement it", type=TaskType.REQUIREMENT)
    record = service.start(
        [item],
        RepositorySpec(
            repo_url=str(remote),
            base_branch="main",
            work_branch="feature/tapd-1",
            push_branch="feature/tapd-1",
        ),
        engine="codex",
        model="test-model",
    )

    assert record.status == RunStatus.WAITING_APPROVAL.value
    assert record.model == "test-model"
    assert record.project_id
    assert record.project_memory_revision == 1
    assert record.engine_session_id == "fake-session"
    assert Path(record.memory_candidate_path).is_file()
    assert Path(record.report_path).is_file()
    assert "- 模型：test-model" in Path(record.report_path).read_text(encoding="utf-8")
    assert git(Path(record.repo_path), "rev-parse", "HEAD") == record.baseline_sha
    assert git(Path(record.repo_path), "remote", "get-url", "--push", "origin").startswith("req2code-disabled://")
    assert subprocess_returncode(Path(record.repo_path), "show-ref", "--verify", "refs/remotes/origin/feature/tapd-1") != 0

    published = service.approve_and_publish(record.run_id, comment="reviewed")
    assert published.status == RunStatus.COMPLETED.value
    assert published.commit_sha
    assert published.project_memory_revision == 2
    assert published.project_memory_source_sha == published.commit_sha
    assert published.memory_candidate_path == ""
    assert "approved implementation" in service.projects.read_documents(published.project_id)["overview"]
    assert git(Path(record.repo_path), "remote", "get-url", "--push", "origin") == record.push_url
    assert git(Path(record.repo_path), "rev-parse", "origin/feature/tapd-1") == published.commit_sha


def test_rejection_discards_memory_candidate_without_promotion(tmp_path, monkeypatch):
    remote = create_remote(tmp_path)
    cfg = AgentConfig()
    cfg.system.state_dir = str(tmp_path / "state")
    cfg.engines.codex.command = f'"{sys.executable}"'
    cfg.review.approvals_file = str(tmp_path / "approvals.yaml")
    cfg.message.webhook = ""
    cfg.testing.unit_command = 'python -c "print(1)"'
    cfg.testing.coverage_command = 'python -c "print(\'TOTAL 1 0 100%\')"'

    service = WorkflowService(cfg)
    monkeypatch.setattr(service, "_runner", lambda engine=None: (FakeRunner(), "codex"))
    record = service.start(
        [WorkItem(id="TAPD-R", title="Reject", description="Reject it", type=TaskType.BUG)],
        RepositorySpec(
            repo_url=str(remote),
            base_branch="main",
            work_branch="feature/reject",
            push_branch="feature/reject",
        ),
        engine="codex",
    )
    candidate = Path(record.memory_candidate_path)
    assert candidate.is_file()

    rejected = service.reject(record.run_id, comment="not accepted")
    assert rejected.status == RunStatus.REJECTED.value
    assert rejected.memory_candidate_path == ""
    assert not candidate.exists()
    project = service.projects.require(record.project_id)
    assert project.memory_revision == 1
    assert "approved implementation" not in service.projects.read_documents(record.project_id)["overview"]

def test_workflow_rejects_agent_commit_and_keeps_push_disabled(tmp_path, monkeypatch):
    remote = create_remote(tmp_path)
    cfg = AgentConfig()
    cfg.system.state_dir = str(tmp_path / "state")
    cfg.engines.codex.command = f'"{sys.executable}"'
    cfg.review.approvals_file = "approvals.yaml"
    cfg.message.webhook = ""
    service = WorkflowService(cfg)
    monkeypatch.setattr(service, "_runner", lambda engine=None: (CommittingRunner(), "codex"))
    item = WorkItem(id="TAPD-2", title="Feature", description="Implement it", type=TaskType.REQUIREMENT)

    with pytest.raises(Exception, match="must not commit"):
        service.start(
            [item],
            RepositorySpec(
                repo_url=str(remote),
                base_branch="main",
                work_branch="feature/tapd-2",
                push_branch="feature/tapd-2",
            ),
            engine="codex",
        )

    record = service.runs.list()[0]
    assert record.status == RunStatus.STALE.value
    assert git(Path(record.repo_path), "remote", "get-url", "--push", "origin").startswith("req2code-disabled://")
    assert subprocess_returncode(
        Path(record.repo_path),
        "show-ref",
        "--verify",
        "refs/remotes/origin/feature/tapd-2",
    ) != 0


def test_current_agent_run_builds_brief_verifies_and_waits_for_approval(tmp_path):
    remote = create_remote(tmp_path)
    cfg = AgentConfig()
    cfg.system.state_dir = str(tmp_path / "state")
    cfg.review.approvals_file = "approvals.yaml"
    cfg.message.webhook = ""
    cfg.testing.unit_command = 'python -c "print(1)"'
    cfg.testing.script_command = ""
    cfg.testing.coverage_command = 'python -c "print(\'TOTAL 1 0 100%\')"'
    cfg.testing.min_coverage = 80

    service = WorkflowService(cfg)
    record = service.begin_agent_run(
        [
            WorkItem(
                id="TAPD-AGENT",
                title="Agent native",
                description="<p>Implement directly</p><p>Acceptance: add a regression test.</p>",
                type=TaskType.BUG,
                metadata={
                    "Bug": {
                        "status": "new",
                        "priority": "high",
                        "severity": "serious",
                        "current_owner": "Developer;",
                        "reporter": "Reporter",
                        "modified": "2026-08-15 21:00:00",
                    }
                },
            )
        ],
        RepositorySpec(
            repo_url=str(remote),
            base_branch="main",
            work_branch="feature/current-agent",
            push_branch="feature/current-agent",
        ),
        agent_name="codex",
    )

    assert record.status == RunStatus.DEVELOPING.value
    assert record.execution_mode == "current_agent"
    assert "finalize_development_run" in record.task_brief
    assert "不得提交" in record.task_brief
    assert "TAPD 完整说明与验收范围" in record.task_brief
    assert "Acceptance: add a regression test." in record.task_brief
    assert "- 状态: new" in record.task_brief
    assert "- 优先级: high" in record.task_brief
    assert "- 负责人: Developer" in record.task_brief
    assert "## 完成标准" in record.task_brief
    assert git(Path(record.repo_path), "rev-parse", "HEAD") == record.baseline_sha

    (Path(record.repo_path) / "agent-native.txt").write_text("implemented\n", encoding="utf-8")
    verified = service.verify_agent_run(
        record.run_id,
        implementation_plan="Add the requested behavior and its tests.",
        implementation_summary="Added agent-native.txt.",
        test_evidence="Targeted test passed.",
    )

    assert verified.status == RunStatus.WAITING_APPROVAL.value
    assert verified.verification_count == 1
    assert "agent-native.txt" in verified.changed_files
    assert Path(verified.report_path).is_file()
    report = Path(verified.report_path).read_text(encoding="utf-8")
    assert "执行方式：当前代码智能体（`current_agent`）" in report
    assert "Targeted test passed" in report
    assert git(Path(record.repo_path), "rev-parse", "HEAD") == record.baseline_sha
    assert git(Path(record.repo_path), "remote", "get-url", "--push", "origin").startswith("req2code-disabled://")


def test_current_agent_finalization_records_evidence_without_rerunning_tests(tmp_path):
    remote = create_remote(tmp_path)
    cfg = AgentConfig()
    cfg.system.state_dir = str(tmp_path / "state")
    cfg.review.approvals_file = "approvals.yaml"
    cfg.message.webhook = ""
    cfg.testing.unit_command = 'python -c "raise SystemExit(99)"'
    cfg.testing.coverage_command = 'python -c "raise SystemExit(98)"'

    service = WorkflowService(cfg)
    record = service.begin_agent_run(
        [WorkItem(id="TAPD-FINAL", title="Finalize", description="Use agent evidence", type=TaskType.BUG)],
        RepositorySpec(
            repo_url=str(remote),
            base_branch="main",
            work_branch="feature/finalize",
            push_branch="feature/finalize",
        ),
        agent_name="claude-code",
    )
    (Path(record.repo_path) / "finalized.txt").write_text("done\n", encoding="utf-8")

    finalized = service.finalize_agent_run(
        record.run_id,
        implementation_plan="Implement the selected defect and add a regression test.",
        implementation_summary="Implemented the defect fix and regression coverage.",
        test_evidence="python -m pytest tests/test_feature.py -q: 4 passed",
        tests_passed=True,
        coverage=92.5,
    )

    assert finalized.status == RunStatus.WAITING_APPROVAL.value
    assert finalized.test_result["source"] == "current_coding_agent"
    assert finalized.test_result["rerun_configured_tests"] is False
    assert finalized.test_result["coverage"] == 92.5
    report = Path(finalized.report_path).read_text(encoding="utf-8")
    assert report.startswith("# Req2Code 开发审核报告")
    assert "证据来源：当前代码智能体" in report
    assert "Req2Code 是否重新执行配置测试：否" in report
    assert "发布分支：仅在审核通过后的第二次发布确认界面中显示" in report
    assert "提交和推送保持锁定" in report


def test_current_agent_failed_test_report_requests_changes_without_rerun(tmp_path):
    remote = create_remote(tmp_path)
    cfg = AgentConfig()
    cfg.system.state_dir = str(tmp_path / "state")
    cfg.review.approvals_file = "approvals.yaml"
    cfg.message.webhook = ""

    service = WorkflowService(cfg)
    record = service.begin_agent_run(
        [WorkItem(id="TAPD-FAIL", title="Fail", description="Report failure", type=TaskType.BUG)],
        RepositorySpec(
            repo_url=str(remote),
            base_branch="main",
            work_branch="feature/finalize-fail",
            push_branch="feature/finalize-fail",
        ),
        agent_name="cursor",
    )
    (Path(record.repo_path) / "failed.txt").write_text("incomplete\n", encoding="utf-8")

    finalized = service.finalize_agent_run(
        record.run_id,
        implementation_plan="Attempt the fix.",
        implementation_summary="The implementation still has a failing boundary test.",
        test_evidence="python -m pytest -q: 1 failed, 3 passed",
        tests_passed=False,
    )

    assert finalized.status == RunStatus.CHANGES_REQUESTED.value
    assert "测试失败或验证不完整" in finalized.approval_comment


def test_current_agent_transient_finalization_error_is_retryable_and_keeps_push_disabled(tmp_path, monkeypatch):
    remote = create_remote(tmp_path)
    cfg = AgentConfig()
    cfg.system.state_dir = str(tmp_path / "state")
    cfg.review.approvals_file = "approvals.yaml"
    cfg.message.webhook = ""
    service = WorkflowService(cfg)
    record = service.begin_agent_run(
        [WorkItem(id="TAPD-TRANSIENT", title="Retry finalization", description="Retry safely", type=TaskType.BUG)],
        RepositorySpec(
            repo_url=str(remote),
            base_branch="main",
            work_branch="feature/transient-finalization",
            push_branch="feature/transient-finalization",
        ),
        agent_name="codex",
    )
    (Path(record.repo_path) / "transient.txt").write_text("done\n", encoding="utf-8")
    original_assert_baseline = service.workspace.assert_baseline
    attempts = 0

    def fail_once(*args, **kwargs):
        nonlocal attempts
        attempts += 1
        if attempts == 1:
            raise RepositoryError("temporary local Git validation error")
        return original_assert_baseline(*args, **kwargs)

    monkeypatch.setattr(service.workspace, "assert_baseline", fail_once)
    with pytest.raises(RepositoryError, match="temporary local Git validation error"):
        service.finalize_agent_run(
            record.run_id,
            implementation_plan="实现并验证所选缺陷。",
            implementation_summary="已实现并补充回归测试。",
            test_evidence="聚焦测试：2 passed",
        )

    interrupted = service.runs.require(record.run_id)
    assert interrupted.status == RunStatus.DEVELOPING.value
    assert interrupted.analysis == "实现并验证所选缺陷。"
    assert interrupted.agent_test_evidence == "聚焦测试：2 passed"
    assert interrupted.verification_count == 1
    assert git(Path(record.repo_path), "remote", "get-url", "--push", "origin").startswith("req2code-disabled://")
    assert "开发中（可继续收尾）" in Path(interrupted.report_path).read_text(encoding="utf-8")

    finalized = service.finalize_agent_run(
        record.run_id,
        implementation_plan="实现并验证所选缺陷。",
        implementation_summary="已实现并补充回归测试。",
        test_evidence="聚焦测试：2 passed",
    )
    assert finalized.status == RunStatus.WAITING_APPROVAL.value
    assert finalized.verification_count == 2
    assert git(Path(record.repo_path), "remote", "get-url", "--push", "origin").startswith("req2code-disabled://")


def test_legacy_failed_finalization_can_recover_and_reprotect_push(tmp_path):
    remote = create_remote(tmp_path)
    cfg = AgentConfig()
    cfg.system.state_dir = str(tmp_path / "state")
    cfg.review.approvals_file = "approvals.yaml"
    cfg.message.webhook = ""
    service = WorkflowService(cfg)
    record = service.begin_agent_run(
        [WorkItem(id="TAPD-LEGACY", title="Legacy failure", description="Recover it", type=TaskType.REQUIREMENT)],
        RepositorySpec(
            repo_url=str(remote),
            base_branch="main",
            work_branch="feature/legacy-finalization",
            push_branch="feature/legacy-finalization",
        ),
        agent_name="codex",
    )
    (Path(record.repo_path) / "legacy.txt").write_text("done\n", encoding="utf-8")
    record.status = RunStatus.FAILED.value
    record.error = "git branch --show-current timed out"
    service.runs.save(record)
    service.workspace.restore_push_url(record.repo_path, record.remote_name, record.push_url)

    finalized = service.finalize_agent_run(
        record.run_id,
        implementation_plan="恢复旧版失败运行。",
        implementation_summary="实现已完成。",
        test_evidence="聚焦测试通过。",
    )
    assert finalized.status == RunStatus.WAITING_APPROVAL.value
    assert finalized.error == ""
    assert git(Path(record.repo_path), "remote", "get-url", "--push", "origin").startswith("req2code-disabled://")


def test_current_agent_can_fix_changes_requested_and_verify_again(tmp_path):
    remote = create_remote(tmp_path)
    cfg = AgentConfig()
    cfg.system.state_dir = str(tmp_path / "state")
    cfg.review.approvals_file = "approvals.yaml"
    cfg.message.webhook = ""
    cfg.testing.unit_command = 'python -c "raise SystemExit(1)"'
    cfg.testing.coverage_command = 'python -c "print(\'TOTAL 1 0 100%\')"'

    service = WorkflowService(cfg)
    record = service.begin_agent_run(
        [WorkItem(id="TAPD-RETRY", title="Retry", description="Fix and retry", type=TaskType.BUG)],
        RepositorySpec(
            repo_url=str(remote),
            base_branch="main",
            work_branch="feature/retry",
            push_branch="feature/retry",
        ),
        agent_name="codex",
    )
    (Path(record.repo_path) / "retry.txt").write_text("first\n", encoding="utf-8")

    first = service.verify_agent_run(record.run_id, "Plan", "First attempt")
    assert first.status == RunStatus.CHANGES_REQUESTED.value
    assert git(Path(record.repo_path), "remote", "get-url", "--push", "origin").startswith("req2code-disabled://")

    cfg.testing.unit_command = 'python -c "print(1)"'
    second = service.verify_agent_run(record.run_id, "Plan", "Fixed the failing behavior")
    assert second.status == RunStatus.WAITING_APPROVAL.value
    assert second.verification_count == 2


def test_review_report_maps_results_to_each_selected_item_and_can_request_changes(tmp_path):
    remote = create_remote(tmp_path)
    cfg = AgentConfig()
    cfg.system.state_dir = str(tmp_path / "state")
    cfg.review.approvals_file = "approvals.yaml"
    cfg.message.webhook = ""
    service = WorkflowService(cfg)
    record = service.begin_agent_run(
        [
            WorkItem(id="DEMO-REQ-001", title="示例需求", description="公开演示需求说明", type=TaskType.REQUIREMENT),
            WorkItem(id="DEMO-BUG-001", title="示例缺陷", description="公开演示缺陷说明", type=TaskType.BUG),
        ],
        RepositorySpec(
            repo_url=str(remote),
            base_branch="main",
            work_branch="feature/multi-review",
            push_branch="feature/multi-review",
        ),
        agent_name="codex",
    )
    (Path(record.repo_path) / "combined.txt").write_text("implemented\n", encoding="utf-8")
    finalized = service.finalize_agent_run(
        record.run_id,
        implementation_plan="统一封装删除确认逻辑。",
        implementation_summary="两个入口已接入确认流程。",
        test_evidence="pytest focused: 4 passed",
        item_results=[
            {
                "item_id": "DEMO-REQ-001",
                "solution": "在删除动作前增加确认对话框。",
                "changes": "项目详情入口调用统一确认逻辑。",
                "changed_files": ["combined.txt"],
                "test_evidence": "删除确认用例 2 passed",
                "acceptance_result": "二次确认生效",
                "residual_risks": "无已知风险",
            },
            {
                "item_id": "DEMO-BUG-001",
                "solution": "取消分支提前返回。",
                "changes": "取消时不触发删除请求。",
                "changed_files": ["combined.txt"],
                "test_evidence": "取消删除用例 2 passed",
                "acceptance_result": "取消后数据保持不变",
                "residual_risks": "无已知风险",
            },
        ],
    )

    assert finalized.status == RunStatus.WAITING_APPROVAL.value
    assert [result["item_id"] for result in finalized.item_results] == ["DEMO-REQ-001", "DEMO-BUG-001"]
    assert finalized.publish_nonce
    report = Path(finalized.report_path).read_text(encoding="utf-8")
    assert "项目详情入口调用统一确认逻辑" in report
    assert "取消时不触发删除请求" in report
    assert "当前没有提交或推送目标生效" in report

    returned = service.request_changes_from_ui(finalized.run_id, finalized.publish_nonce, "请补充键盘交互测试")
    assert returned.status == RunStatus.CHANGES_REQUESTED.value
    assert returned.publish_nonce == ""
    assert "键盘交互测试" in returned.approval_comment
    assert git(Path(record.repo_path), "rev-parse", "HEAD") == record.baseline_sha
    assert git(Path(record.repo_path), "remote", "get-url", "--push", "origin").startswith("req2code-disabled://")


def test_ui_publication_requires_private_nonce_and_second_confirmation(tmp_path):
    remote = create_remote(tmp_path)
    cfg = AgentConfig()
    cfg.system.state_dir = str(tmp_path / "state")
    cfg.review.approvals_file = "approvals.yaml"
    cfg.message.webhook = ""
    service = WorkflowService(cfg)
    record = service.begin_agent_run(
        [WorkItem(id="BUG-PUBLISH", title="发布门禁", description="双重确认", type=TaskType.BUG)],
        RepositorySpec(
            repo_url=str(remote),
            base_branch="main",
            work_branch="feature/ui-publish",
            push_branch="feature/ui-publish",
        ),
        agent_name="codex",
    )
    (Path(record.repo_path) / "publish.txt").write_text("ready\n", encoding="utf-8")
    finalized = service.finalize_agent_run(
        record.run_id,
        implementation_plan="增加双重确认门禁。",
        implementation_summary="实现完成。",
        test_evidence="2 passed",
    )

    with pytest.raises(PermissionError, match="审核会话已失效"):
        service.approve_and_publish_from_ui(finalized.run_id, "wrong", "确认提交并推送")
    with pytest.raises(ValueError, match="明确确认"):
        service.approve_and_publish_from_ui(finalized.run_id, finalized.publish_nonce, "审核通过")
    assert git(Path(record.repo_path), "rev-parse", "HEAD") == record.baseline_sha
    assert subprocess_returncode(Path(record.repo_path), "show-ref", "--verify", "refs/remotes/origin/feature/ui-publish") != 0

    published = service.approve_and_publish_from_ui(
        finalized.run_id,
        finalized.publish_nonce,
        "确认提交并推送",
        "界面二次确认通过",
    )
    assert published.status == RunStatus.COMPLETED.value
    assert published.publish_nonce == ""
    assert published.commit_sha
    assert git(Path(record.repo_path), "rev-parse", "origin/feature/ui-publish") == published.commit_sha


def subprocess_returncode(path: Path, *args: str) -> int:
    return subprocess.run(["git", *args], cwd=path, capture_output=True, check=False).returncode
